language: node_js
node_js:
  - "7"
sudo: required
services:
  - docker

before_install:
  - docker build -t subashthapa1110/docker-react -f Dockerfile.dev .

script:
  -  -docker run -e CI=true subashthapa1110/docker-react npm run test